-- AlterTable
ALTER TABLE `user` ADD COLUMN `active` ENUM('ACTIVE', 'INACTIVE', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN `deletedAt` DATETIME(3) NULL,
    ADD COLUMN `locked` BOOLEAN NOT NULL DEFAULT false;
